# ExplosiveArrows v0.0.1_ALPHA - Settings.yml configeration file

# Should explosions do damage to terrain?
terrain-damage: false

# Default explosion size (When it isn't defined by NBT)
default-explosion-size: 4