--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/JackNoordhuis/PocketMine-Plugins
branches:
- master
projects:
  CombatLogger:
    path: CombatLogger/
  EffectEventTesting:
    path: EffectEventTesting/
  ExplosiveArrows:
    path: ExplosiveArrows/
...
